//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WheelyRev.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int productID { get; set; }
        public string ImagePath { get; set; }
        public string productDescription { get; set; }
        public decimal productPrice { get; set; }
        public int productQty { get; set; }
        public Nullable<int> shopId { get; set; }
        public string productName { get; set; }
    
        public virtual Shops Shops { get; set; }
    }
}
